services:
  gbif-nginx:
    image: nginx:latest
    container_name: gbif-nginx
    restart: unless-stopped
    volumes:
      - ./gbif-nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - gbif-net
      - edge-net   
    depends_on:
      - gbif-app

  gbif-app:
    image: ghcr.io/benjaminhlina/biodiversity-app:latest 
    volumes:
      - /opt/gbif/:/srv/shiny-server/gbif-app/:ro 
    restart: unless-stopped
    expose:
      - "3838"
    networks:
      - gbif-net

networks:
  gbif-net:
    driver: bridge
  edge-net:
    external: true